---
# Kustomization - Apply all ArgoCD Applications
# Usage: kubectl apply -k /path/to/core-cluster/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - applications/victoria-metrics-single.yaml
  - applications/vmagent.yaml
  - applications/alertmanager.yaml
  - applications/grafana.yaml
  - applications/prometheus.yaml
  - applications/kube-state-metrics.yaml

commonLabels:
  app.kubernetes.io/part-of: core-monitoring
  environment: core
