apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - applications/victoria-metrics-single.yaml
  - applications/vmagent.yaml
  - applications/vmalert.yaml
  - applications/grafana.yaml
  - applications/prometheus.yaml
  - applications/kube-state-metrics.yaml
